import raw from './photos.json'

// Generated by scripts/photos.py. Edit alt text and captions in photos.json.
export interface Photo {
  id: string
  width: number
  height: number
  color: string
  alt: string
  caption: string
}

export const photos: Photo[] = raw

const base = `${import.meta.env.BASE_URL}photos/`

export const photoSrc = (p: Photo, size: 640 | 1280 | 2560, ext: 'webp' | 'jpg' = 'webp') => `${base}${p.id}-${size}.${ext}`

export const photoSrcSet = (p: Photo) =>
  ([640, 1280, 2560] as const)
    .map((s) => {
      // Files are never upscaled, so the largest one may be smaller than its name says.
      const long = Math.max(p.width, p.height)
      return `${photoSrc(p, s)} ${Math.round((p.width * Math.min(s, long)) / long)}w`
    })
    .join(', ')
